// LeetCode URL helper and directory mapping

const problemUrlMap: Record<string, string> = {
  'Two Sum': 'https://leetcode.com/problems/two-sum/',
  'Best Time to Buy and Sell Stock': 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
  'Best Time to Buy Stock': 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
  'Contains Duplicate': 'https://leetcode.com/problems/contains-duplicate/',
  'Product of Array Except Self': 'https://leetcode.com/problems/product-of-array-except-self/',
  'Maximum Subarray': 'https://leetcode.com/problems/maximum-subarray/',
  'Merge Intervals': 'https://leetcode.com/problems/merge-intervals/',
  '3Sum': 'https://leetcode.com/problems/3sum/',
  'Trapping Rain Water': 'https://leetcode.com/problems/trapping-rain-water/',
  'Sliding Window Maximum': 'https://leetcode.com/problems/sliding-window-maximum/',
  'First Missing Positive': 'https://leetcode.com/problems/first-missing-positive/',
  'Container With Most Water': 'https://leetcode.com/problems/container-with-most-water/',
  'Subarray Sum Equals K': 'https://leetcode.com/problems/subarray-sum-equals-k/',
  'Rotate Image': 'https://leetcode.com/problems/rotate-image/',
  'Spiral Matrix': 'https://leetcode.com/problems/spiral-matrix/',
  'Set Matrix Zeroes': 'https://leetcode.com/problems/set-matrix-zeroes/',
  'Longest Consecutive Sequence': 'https://leetcode.com/problems/longest-consecutive-sequence/',
  'Search in Rotated Sorted Array': 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
  'Find Minimum in Rotated Sorted Array': 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
  'Time Based Key-Value Store': 'https://leetcode.com/problems/time-based-key-value-store/',
  'Koko Eating Bananas': 'https://leetcode.com/problems/koko-eating-bananas/',
  'Longest Substring Without Repeating': 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
  'Valid Palindrome': 'https://leetcode.com/problems/valid-palindrome/',
  'Group Anagrams': 'https://leetcode.com/problems/group-anagrams/',
  'Minimum Window Substring': 'https://leetcode.com/problems/minimum-window-substring/',
  'Valid Parentheses': 'https://leetcode.com/problems/valid-parentheses/',
  'Longest Palindromic Substring': 'https://leetcode.com/problems/longest-palindromic-substring/',
  'Valid Anagram': 'https://leetcode.com/problems/valid-anagram/',
  'Encode and Decode Strings': 'https://leetcode.com/problems/encode-and-decode-strings/',
  'Palindromic Substrings': 'https://leetcode.com/problems/palindromic-substrings/',
  'String to Integer (atoi)': 'https://leetcode.com/problems/string-to-integer-atoi/',
  'Longest Common Prefix': 'https://leetcode.com/problems/longest-common-prefix/',
  'Reverse Linked List': 'https://leetcode.com/problems/reverse-linked-list/',
  'Merge Two Sorted Lists': 'https://leetcode.com/problems/merge-two-sorted-lists/',
  'Add Two Numbers': 'https://leetcode.com/problems/add-two-numbers/',
  'Merge K Sorted Lists': 'https://leetcode.com/problems/merge-k-sorted-lists/',
  'Remove Nth Node From End of List': 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
  'Reorder List': 'https://leetcode.com/problems/reorder-list/',
  'Linked List Cycle': 'https://leetcode.com/problems/linked-list-cycle/',
  'Linked List Cycle II': 'https://leetcode.com/problems/linked-list-cycle-ii/',
  'Copy List with Random Pointer': 'https://leetcode.com/problems/copy-list-with-random-pointer/',
  'LRU Cache': 'https://leetcode.com/problems/lru-cache/',
  'Validate BST': 'https://leetcode.com/problems/validate-binary-search-tree/',
  'Binary Tree Level Order': 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
  'Maximum Depth of Binary Tree': 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
  'Serialize and Deserialize BT': 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',
  'Serialize Binary Tree': 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',
  'Binary Tree Zigzag Level': 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/',
  'Lowest Common Ancestor': 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',
  'Invert Binary Tree': 'https://leetcode.com/problems/invert-binary-tree/',
  'Subtree of Another Tree': 'https://leetcode.com/problems/subtree-of-another-tree/',
  'Diameter of Binary Tree': 'https://leetcode.com/problems/diameter-of-binary-tree/',
  'Balanced Binary Tree': 'https://leetcode.com/problems/balanced-binary-tree/',
  'Same Tree': 'https://leetcode.com/problems/same-tree/',
  'Binary Tree Right Side View': 'https://leetcode.com/problems/binary-tree-right-side-view/',
  'Construct Binary Tree from Preorder and Inorder': 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',
  'Kth Smallest Element in a BST': 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
  'Lowest Common Ancestor of BST': 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
  'Number of Islands': 'https://leetcode.com/problems/number-of-islands/',
  'Course Schedule': 'https://leetcode.com/problems/course-schedule/',
  'Course Schedule II': 'https://leetcode.com/problems/course-schedule-ii/',
  'Clone Graph': 'https://leetcode.com/problems/clone-graph/',
  'Word Ladder': 'https://leetcode.com/problems/word-ladder/',
  'Pacific Atlantic Water Flow': 'https://leetcode.com/problems/pacific-atlantic-water-flow/',
  'Number of Connected Components': 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/',
  'Graph Valid Tree': 'https://leetcode.com/problems/graph-valid-tree/',
  'Rotting Oranges': 'https://leetcode.com/problems/rotting-oranges/',
  'Network Delay Time': 'https://leetcode.com/problems/network-delay-time/',
  'Cheapest Flights Within K Stops': 'https://leetcode.com/problems/cheapest-flights-within-k-stops/',
  'Alien Dictionary': 'https://leetcode.com/problems/alien-dictionary/',
  'Word Search': 'https://leetcode.com/problems/word-search/',
  'Combination Sum': 'https://leetcode.com/problems/combination-sum/',
  'Combination Sum II': 'https://leetcode.com/problems/combination-sum-ii/',
  'Permutations': 'https://leetcode.com/problems/permutations/',
  'Subsets': 'https://leetcode.com/problems/subsets/',
  'Subsets II': 'https://leetcode.com/problems/subsets-ii/',
  'Letter Combinations of a Phone Number': 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',
  'Palindrome Partitioning': 'https://leetcode.com/problems/palindrome-partitioning/',
  'N-Queens': 'https://leetcode.com/problems/n-queens/',
  'Kth Largest Element in an Array': 'https://leetcode.com/problems/kth-largest-element-in-an-array/',
  'Top K Frequent Elements': 'https://leetcode.com/problems/top-k-frequent-elements/',
  'Find Median from Data Stream': 'https://leetcode.com/problems/find-median-from-data-stream/',
  'Task Scheduler': 'https://leetcode.com/problems/task-scheduler/',
  'Daily Temperatures': 'https://leetcode.com/problems/daily-temperatures/',
  'Evaluate Reverse Polish Notation': 'https://leetcode.com/problems/evaluate-reverse-polish-notation/',
  'Largest Rectangle in Histogram': 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
  'Decode String': 'https://leetcode.com/problems/decode-string/',
  'Climbing Stairs': 'https://leetcode.com/problems/climbing-stairs/',
  'House Robber': 'https://leetcode.com/problems/house-robber/',
  'Coin Change': 'https://leetcode.com/problems/coin-change/',
  'Coin Change II': 'https://leetcode.com/problems/coin-change-ii/',
  'Longest Common Subsequence': 'https://leetcode.com/problems/longest-common-subsequence/',
  'Unique Paths': 'https://leetcode.com/problems/unique-paths/',
  'Word Break': 'https://leetcode.com/problems/word-break/',
  'Edit Distance': 'https://leetcode.com/problems/edit-distance/',
  'Longest Increasing Subsequence': 'https://leetcode.com/problems/longest-increasing-subsequence/',
  'Maximum Product Subarray': 'https://leetcode.com/problems/maximum-product-subarray/',
  'Partition Equal Subset Sum': 'https://leetcode.com/problems/partition-equal-subset-sum/',
  'Target Sum': 'https://leetcode.com/problems/target-sum/',
  'Interleaving String': 'https://leetcode.com/problems/interleaving-string/',
  'Min Stack': 'https://leetcode.com/problems/min-stack/',
  'Design Hit Counter': 'https://leetcode.com/problems/design-hit-counter/',
  'Design Search Autocomplete': 'https://leetcode.com/problems/design-search-autocomplete-system/',
  'Implement Trie': 'https://leetcode.com/problems/implement-trie-prefix-tree/',
  'Word Search II': 'https://leetcode.com/problems/word-search-ii/',
  'Median of Two Sorted Arrays': 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
  'Regular Expression Matching': 'https://leetcode.com/problems/regular-expression-matching/',
  'Next Permutation': 'https://leetcode.com/problems/next-permutation/',
  'Snapshot Array': 'https://leetcode.com/problems/snapshot-array/',
  'Decode Ways': 'https://leetcode.com/problems/decode-ways/',
  'Pow(x, n)': 'https://leetcode.com/problems/powx-n/',
}

export function getLeetCodeUrl(title: string): string {
  if (problemUrlMap[title]) {
    return problemUrlMap[title]
  }
  // Fallback: slugify title cleanly
  const slug = title
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
  return `https://leetcode.com/problems/${slug}/`
}
